name: Math Utility with Maven & CI using GitHub Actions| © 2023 by lucas

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8 - mượn JDK cua Mỹ
      uses: actions/setup-java@v3
      with:
        java-version: '1.8'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven - ĐÓNG GÓI .JAR BẰNG LỆNH MVN KO CÓ COLOR 4E
      run: mvn -B package --file pom.xml
    - name: Distribute jar-war file # Gửi file .jar .war đi đâu, CD nhảy vào ...
      run: mkdir staging && cp target/*.jar staging # tạo thư mục staging chứa file .jar .war sau khi build      
     
    - name: Make hyperlink to jar-war file # Tạo hyperlink để download build 
      uses: actions/upload-artifact@v1
      with:
        name: 1.0-SNAPSHOT.jar # Bản build được nén thành .zip để lát hồi mọi người download về
        path: staging

    
